language: node_js
node_js:
  - 10
  - 12

script:
  - yarn test

before_deploy:
  - yarn build

deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_API_KEY
  skip_cleanup: true
  on:
    branch: master
